### ISSUE TITLE
Please publish a new release compatible with GHC 9.2

### ISSUE THREAD

**Issue by mordae** [agrafix/hvect#3]
Hi, would it be possible for you to publish a new release with the recent GHC 9.2 patch?

PS:
Thank you for sharing the library the first place, it has been a great help!
It is far better to use your implementation than to reinvent it independently for every other project.

**Comment by agrafix** [comment]
done! :) 

let me know if you'd me interested in helping maintain the library.

**Comment by mordae** [comment]
If I ever release my packages that depend on it and learn the Hackage ropes, I will consider your offer.
